# Generated by Django 4.0.6 on 2022-08-03 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=50, null=True)),
                ('r_image', models.ImageField(null=True, upload_to='images')),
                ('r_number', models.IntegerField(default=0)),
                ('r_manager_name', models.CharField(max_length=50, null=True)),
                ('r_manager_number', models.IntegerField(default=0)),
                ('r_email', models.EmailField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('f_type', models.CharField(choices=[('Fruit and vegetables', 'Fruit and vegetables'), ('Starchy food', 'Starchy food'), ('Dairy', 'Dairy'), ('Protein', 'Protein'), ('Fat', 'Fat')], default='vagetarian', max_length=50)),
                ('food_price', models.FloatField()),
                ('food_image', models.ImageField(blank=True, upload_to='images/food_image')),
                ('food_description', models.TextField(blank=True, max_length=200)),
                ('r_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_name', to='restaurant.restaurantuser')),
            ],
        ),
    ]
